name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set chmod to Gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/*.apk"
          artifactContentType: "application/vnd.android.package-archive"
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
